import type { Metadata } from "next";
import { Open_Sans, Poppins } from "next/font/google";
import "./globals.css";

const open_sans = Open_Sans({ 
  subsets: ["latin"],
  variable: '--font-openSans',
  display: "swap"
});
const poppins = Poppins({ 
  subsets: ["latin"], 
  weight: "400",
  variable: '--font-poppins',
  display: "swap"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${open_sans.variable} ${poppins.variable}`}>{children}</body>
    </html>
  );
}
